---
title: "HappyDB Analysis"
author: "Your Name"
output: html_document
---

## Introduction

This analysis focuses on understanding the factors that contribute to happiness, based on the HappyDB dataset.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(DT)
library(scales)
library(wordcloud2)
library(gridExtra)
library(ngram)
library(shiny)

# Load the processed text data along with demographic information on contributors
hm_data <- read_csv("../output/processed_moments.csv")

urlfile<-'https://raw.githubusercontent.com/rit-public/HappyDB/master/happydb/data/demographic.csv'
demo_data <- read_csv(urlfile)

# Combine both the data sets and keep the required columns for analysis
hm_data <- hm_data %>%
  inner_join(demo_data, by = "wid") %>%
  select(wid,
         original_hm,
         gender, 
         marital, 
         parenthood,
         reflection_period,
         age, 
         country, 
         ground_truth_category, 
         text) %>%
  mutate(count = sapply(hm_data$text, wordcount))

# Gender-based analysis
gender_analysis <- hm_data %>%
  group_by(gender) %>%
  summarise(avg_count = mean(count))

ggplot(gender_analysis, aes(x = gender, y = avg_count)) +
  geom_bar(stat = "identity") +
  ggtitle("Average Word Count by Gender")

